### PR TITLE
change cursor to pointer

### PR DESCRIPTION
**Pull request by jayanththalla**
## PR Description 📜

In this project, I have made changes like a pointer to the help, setting, pause, and other buttons.
I also added a cursor when we press the help button it opens for the close help button added cursor.
In setting, I added the cursor to raise the volume, reset the game, and ok.
I added a cursor to the garbage meteor and others
Fixes # 76

<hr>
 
## Mark the task you have completed ✅

- [ x] I follow [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md) & [CODE OF CONDUCT](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x ] I have performed a self-review of my own code or work.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [ x] My changes generates no new warnings.
- [ x] I have followed proper naming convention showed in [CONTRIBUTING GUIDELINE](https://github.com/GameSphere-MultiPlayer/Community-Page/blob/main/.github/CONTRIBUTING_GUIDELINE.md)
- [x ] I have added screenshot for review.

<hr>
## Add your screenshots(Optional) 📸

--- 
<br>

## Thank you soo much for contributing to our repository 💗

### CODE REVIEW

**Comment by jayanththalla** [comment]
label it under gssoc24

**Review by Durgesh4993 — COMMENTED** [review]
Add issue number and demo video

**Comment by Durgesh4993** [comment]
Don't forget to resolve conflict files

**Comment by piyushsahujtp** [comment]
Assign this project to me , I want to do work on this project.

**Comment by jayanththalla** [comment]
> Add issue number and demo video

issue number #53 

Uploading pointer changed.mp4…

**Pull request merged**
